---
- group:
    name: "{{ application_name }}"
    state: present

- user:
    name: "{{ application_name }}"
    group: "{{ application_name }}"
    shell: /usr/sbin/nologin

- name: ensure that there is a folder to install the admin ui in
  file: path=/opt/{{ application_name }} state=directory

- name: ensure that the initial pipeline is present
  copy: src={{ application_jar }} dest=/opt/{{ application_name }}/{{ application_name }}.jar

- name: ensure that upstart configuration is present
  template: src=application.service dest=/lib/systemd/system/{{ application_name }}.service mode=755

- name: "restart {{ application_name }}"
  systemd: name={{ application_name }} state=restarted enabled=true
  async: 45
  poll: 5
